FILE_PATH	:= $(call my-dir)

FILE_OBJS	:= fdt.o
FILE_OBJS	+= fdt_empty_tree.o
FILE_OBJS	+= fdt_ro.o
FILE_OBJS	+= fdt_rw.o
FILE_OBJS	+= fdt_strerror.o
FILE_OBJS	+= fdt_sw.o
FILE_OBJS	+= fdt_wip.o

$(eval $(call register-objs, $(FILE_PATH), $(FILE_OBJS)))
